const PRODUCT_LIST_REQUESTED = "PRODUCT_LIST_REQUESTED";
const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
const PRODUCT_DETAILS_REQUESTED = "PRODUCT_DETAILS_REQUESTED";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const CART_ADD = "CART_ADD";
const CART_REMOVE = "CART_REMOVE";

export { PRODUCT_LIST_REQUESTED, PRODUCT_LIST_SUCCESS, PRODUCT_DETAILS_REQUESTED, PRODUCT_DETAILS_SUCCESS, CART_ADD, CART_REMOVE };
